name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-deps-
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - uses: DeLaGuardo/setup-clojure@master
      with:
        # To use Clojure CLI 1.10.1.561 based on tools.deps
        cli: '1.10.1.469'
    - run: make ci